#error el closure no devuelve un retorno valido#
fun _var4,

fun _f1 ( ) {
integer _x,
_x := 5_i,
void _g () {integer _y, _z := _z + 1_i, print('suma'),}
return(_g),
}